### ISSUE TITLE
--spaces does not seem to work

### ISSUE THREAD

**Issue by Redsandro** [davidfig/json-bump#1]
Hi,

I'm trying to update my `package.json` using two spaces only. I've tried the following commands:

```bash
json-bump package.json --spaces=2
```

```bash
json-bump --spaces=2 package.json
```

In both cases, indentation is made out of 4 spaces.

Am I doing it wrong, or is this a bug?

Node v8.16.0
npm 6.10.1
nvm 0.34.0
Linux 5.2.0 x64

**Comment by davidfig** [comment]
Try 
```
json-bump --spaces 2 package.json
```

Or use yarn (which is what I ended up doing).

**Comment by Redsandro** [comment]
I ended up using good old `sed`. Thanks for the update!
